spring.application.name=groupbuyingweb
server.port = 8088
## 1. ?????? ?? ??
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=jdbctest
#spring.datasource.password=jdbctest
#spring.datasource.url=jdbc:mysql://localhost:3306/group_buying_db?characterEncoding=UTF-8&serverTimezone=UTC

# 1.1 MySQL DataSource
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.mysql.jdbc-url=jdbc:mysql://localhost:3306/group_buying_db?characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.mysql.username=jdbctest
spring.datasource.mysql.password=jdbctest
# JPA & Hibernate - mysql
spring.jpa.mysql.hibernate.ddl-auto=update
spring.jpa.mysql.database-platform=org.hibernate.dialect.MySQLDialect
# ======================================================
# 1.2 H2 DataSource
spring.datasource.h2.driver-class-name=org.h2.Driver
spring.datasource.h2.jdbc-url=jdbc:h2:mem:group_buying_db;MODE=MySQL
spring.datasource.h2.username=sa
spring.datasource.h2.password=
# JPA & Hibernate - h2
spring.jpa.h2.hibernate.ddl-auto=create-drop
spring.jpa.h2.database-platform=org.hibernate.dialect.H2Dialect

# 2. JPA & Hibernate global
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database=mysql
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. ?? ??
logging.level.org.hibernate=info

spring.config.import=optional:file:.env[.properties]

# Kakao Local API - ??? REST API ?
kakao.local.rest-api-key=${KAKAO_REST_API_KEY}

# Kakao JavaScript SDK - Thymeleaf ??? ??? JavaScript ?
kakao.local.javascript-key=${KAKAO_JAVASCRIPT_KEY}

# ?? ?? ??
# file.upload.dir=/Users/kangminju/Desktop/upload/
file.upload.dir=C:/upload/
# dir: C:/upload/ # ????? ?? ??? ??

# ?? ??? ???? ?? ??
spring.servlet.multipart.max-file-size=10MB

# ??(Request) ? ?? ?? ? ?? ?? ???? ?? ??
spring.servlet.multipart.max-request-size=30MB

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
